branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: kudosbot
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: null
